DROP TRIGGER friendship_unique;
DROP TRIGGER cities_id_autogenerate;
DROP TRIGGER message_id_autogenerate;
DROP TRIGGER programs_id_autogenerate;

DROP SEQUENCE CITIES_SEQ;
DROP SEQUENCE MESSAGE_SEQ;
DROP SEQUENCE PROGRAMS_SEQ;

ALTER TABLE TAGS DROP CONSTRAINT TAGS_P_KEY CASCADE;
ALTER TABLE PHOTOS DROP CONSTRAINT PHOTOS_P_KEY CASCADE;
ALTER TABLE ALBUMS DROP CONSTRAINT ALBUMS_P_KEY CASCADE;
ALTER TABLE EDUCATION DROP CONSTRAINT EDUCATION_P_KEY CASCADE;
ALTER TABLE PROGRAMS DROP CONSTRAINT PROGRAMS_P_KEY CASCADE;
ALTER TABLE MESSAGE DROP CONSTRAINT MESSAGE_P_KEY CASCADE;
ALTER TABLE USER_HOMETOWN_CITY DROP CONSTRAINT USER_HOMETOWN_CITY_P_KEY CASCADE;
ALTER TABLE USER_CURRENT_CITY DROP CONSTRAINT USER_CURRENT_CITY_P_KEY CASCADE;
ALTER TABLE CITIES DROP CONSTRAINT CITIES_P_KEY CASCADE;
ALTER TABLE FRIENDS DROP CONSTRAINT FRIENDS_P_KEY CASCADE;
ALTER TABLE USERS DROP CONSTRAINT USERS_P_KEY CASCADE;
ALTER TABLE PARTICIPANTS DROP CONSTRAINT PARTICIPANTS_P_KEY CASCADE;
ALTER TABLE USER_EVENTS DROP CONSTRAINT USER_EVENTS_P_KEY CASCADE;

DROP TABLE TAGS;
DROP TABLE PHOTOS;
DROP TABLE ALBUMS;
DROP TABLE EDUCATION;
DROP TABLE PROGRAMS;
DROP TABLE MESSAGE;
DROP TABLE USER_HOMETOWN_CITY;
DROP TABLE USER_CURRENT_CITY;
DROP TABLE CITIES;
DROP TABLE FRIENDS;
DROP TABLE PARTICIPANTS;
DROP TABLE USER_EVENTS;
DROP TABLE USERS;
